# Generated by Django 3.0.3 on 2020-06-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('prelude', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('pubdate', models.DateField()),
                ('projurlextension', models.URLField(max_length=40, unique=True)),
            ],
        ),
    ]
