# Generated by Django 3.0.3 on 2020-06-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogg',
            name='author',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='blogg',
            name='image',
            field=models.FilePathField(null=True, path='/img'),
        ),
    ]
