# Generated by Django 3.0.3 on 2020-06-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200613_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogg',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
