# Generated by Django 3.0.3 on 2020-06-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200615_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogg',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
