# Generated by Django 3.0.3 on 2020-06-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200615_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogg',
            name='prelude',
            field=models.CharField(default='This post was created before this feature was implemented', max_length=200),
            preserve_default=False,
        ),
    ]
